### ISSUE TITLE
Feature Request: parsing for multiline list items as per Creole 1.0

### ISSUE THREAD

**Issue by irhs** [dokufreaks/plugin-creole#11] opened 2012-11-06 20:57 UTC
As per the multiline specifications for Creole 1.0, list items can be of multiple lines. 
http://www.wikicreole.org/wiki/MultilineListItems

So the following creole code  

```
* item 1
* item 2
This line should be part of item 2.
```

should be rendered as:

```
* item 1
* item 2 This line should be part of item 2.
```

The plugin was written for Creole 0.3 and it renders the above code as:

```
* item 1
* item 2 
This line should be part of item 2.
```

**Comment by LarsGit223** [comment] 2015-08-08 19:40
Done.
There is currently no way to switch back to Creole 0.3 behaviour as this is not requested by the Creole specification.

**Comment by bmolitor** [comment] 2015-08-27 12:46
This leads to headings immediately following a list (e.g. separated by just one newline) not being rendered:

    * List item
    == Heading ==

This might be the expected behaviour, but I don't know - it wold seem logical for headings to have precedence over other markup, but I don't see anything about this in the specification, so this might be working as intended. This becomes a problem when using the "edit section buttons", as it becomes easier to end a section with a list item without remembering that on the full page, a new section heading might follow and require an additional newline in between to render...

**Comment by LarsGit223** [comment] 2015-08-27 17:57
I checked the Creole page and found the following:

> Lists

> List items begin with a * or a # at the beginning of a line. Whitespace is optional before and after the * or # characters, however a space is required afterwards if the list element starts with bold text. **A list item ends at the line which begins with a * or # character (next item or sublist), blank line, heading, table, or nowiki block**; like paragraphs, it can span multiple lines and contain line breaks forced with \\. It is recommended to have support for a depth of at least five levels of nesting. Bold, italics, links, and nowiki can be used in list items, but they cannot span several list items. 

So I would say it's a big and therefore I re-open this issue.

**Comment by LarsGit223** [comment] 2015-09-02 17:31
The issue with the heading immediately following a list is also fixed now. So this should work now:

```
* List item
== Heading ==
```

A horizontal line still requires two new lines = one empty line but not three new lines any more.

**Comment by battlemidget** [comment] 2015-09-15 19:55
I installed the latest zip from master, however, placing

```
* List item
== Heading ==
```

Still renders everything on the same line for me. Am I missing something?

**Comment by bmolitor** [comment] 2015-09-15 20:34
The fix is not merged into master yet. It lives in branch creole10 for
now, which is still in development. To test it, use
https://github.com/dokufreaks/plugin-creole/zipball/creole10

**Comment by battlemidget** [comment] 2015-09-15 20:57
Thanks I tested with branch creole10 and can confirm it is fixed

**Comment by LarsGit223** [comment] 2019-02-06 18:54
The ```creole10``` branch is merged now. The new release version is ```2019-02-06```. So this can be closed.

**Closed by LarsGit223** 2019-02-06 18:54 UTC
Labels: Feature
